// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDha1ANaxG14APy8ebT0k7iMrprIKXuAwE',
    appId: '1:965369886885:web:0664543123786db36cb54c',
    messagingSenderId: '965369886885',
    projectId: 'health-and-habit-d23c9',
    authDomain: 'health-and-habit-d23c9.firebaseapp.com',
    storageBucket: 'health-and-habit-d23c9.appspot.com',
    measurementId: 'G-GHNJ711V0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2cfsC7bzfB9eeo9c_eXsZjleVkE4kuv8',
    appId: '1:965369886885:android:dcbbc42053ab3c286cb54c',
    messagingSenderId: '965369886885',
    projectId: 'health-and-habit-d23c9',
    storageBucket: 'health-and-habit-d23c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOvfN0JQtHz_1mMl9QLIxk0i1UjYtQ5dE',
    appId: '1:965369886885:ios:c057611cdea0f57d6cb54c',
    messagingSenderId: '965369886885',
    projectId: 'health-and-habit-d23c9',
    storageBucket: 'health-and-habit-d23c9.appspot.com',
    iosBundleId: 'com.example.animateYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOvfN0JQtHz_1mMl9QLIxk0i1UjYtQ5dE',
    appId: '1:965369886885:ios:eb0d123110d2cb1e6cb54c',
    messagingSenderId: '965369886885',
    projectId: 'health-and-habit-d23c9',
    storageBucket: 'health-and-habit-d23c9.appspot.com',
    iosBundleId: 'com.example.animateYou.RunnerTests',
  );
}
